expr: Experiment

device: cuda

data:
  dataset: MNIST
  mode: train # should consider train or test!

model:
  name: DDPM
  time_steps: 1000
  beta_schedule: linear

hyperparams:
  optim: Adam
  lr: 0.0002
  weight_decay: ~
  epochs: 100
  batch_size: 16

save_path: saved

load_weights: 